name: CI-CLIENT

on: 
  push:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "edited"
      - "synchronize"
      - "ready_for_review"

jobs:
  eslint-application:
    runs-on: ubuntu-latest
    name: Eslint Application
    container:
      image: node:14-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps
      - name: Install client dependencies
        run: npm i
      - name: Run Tests
        run: npm run lint
